WIDTH, HEIGHT = 1280, 720
INTERP_DELAY = 0.15
MAX_HISTORY = 15
FETCH_INTERVAL = 0.08
SEND_INTERVAL = 0.10
VISIBLE_RADIUS = 10.0
TARGET_FPS = 60
SPRINT = 100
VELOCITY_CORRECTION_SPEED = 0.15
POSITION_CORRECTION_SPEED = 0.08
ROTATION_CORRECTION_SPEED = 0.12
MAX_POSITION_ERROR = 0.5

WORLD_WIDTH = 15
WORLD_HEIGHT = 15

SUPABASE_URL = "https://ciuqcdaowlwztlzkanpq.supabase.co"
SUPABASE_KEY = "sb_publishable_R8sevzo6mu8PBPNaQZSmOg_KKzoqAVR"

if not SUPABASE_URL or not SUPABASE_KEY:
    raise RuntimeError(
        "Supabase configuration missing. "
        "Please set SUPABASE_URL and SUPABASE_KEY environment variables."
    )